DeepONet Example
pnnl/neuromancer pull request #168
Opened 2024-06-28 20:40 UTC by colby-ham

First DeepONet example, wrapping up modifications in this new branch after messy rebase

2024-06-28 23:57 UTC, RBirmiwal commented
This is looking good so far!

2024-07-01 20:51 UTC, drgona requested changes
I like the new DeepONet class abstraction 
- lets add explanation in the docstring on problem dimensions: Nu, Nsamples, in_size_trunk, interact_size
- Lets try to make the example more didactical. We should add a paragraph explaining DeepONet architecture including figure from the paper.
- we need to add more markdown in the code - each cell should have a brief markdown explanation 
- lets avoid the use of undefined acronyms - for instance, its not clear what is 1d grf from deepxde - moreover as far as I can tell these features are not used further in the code - each cell needs to be intentional. We should avoid junk code in the example
- lets avoid cells that generate more than single figure 
- **IMPORTANT**: current example will not run - it expects training data from examples/neural_operators/datasets - Lets generate data by simulating the system not by loading from any file
- I don't see the utility of cell with scipy integrate and associated plot
-

2024-07-01 21:00 UTC, colby-ham commented
Will briefly respond to the comments before our meeting tomorrow. The "1d grf from deepxde" is part of me trying to get the data generation working in the example and that is also the reason why multiple plots are being show for my debugging purposes. I talked to @brunopjacob and think I have a way forward for data generation. The extra changes from Trainer and Problem are accidental from code reformat. I will pull a fresh copy and only put the changes necessary Trainer ( loss history), Problem (predict)

2024-12-02 17:10 UTC, RBirmiwal commented
@brunopjacob Let's plan to finish this this week

2026-01-09 19:03 UTC, Parv621 commented
@drgona This PR can be deleted as #265 covers it fully

2026-01-10 15:33 UTC, closed without merging